/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface WcHeatMap {
        "enddate": any;
        "height": number;
        "startdate": any;
        "width": number;
    }
}
declare global {
    interface HTMLWcHeatMapElement extends Components.WcHeatMap, HTMLStencilElement {
    }
    var HTMLWcHeatMapElement: {
        prototype: HTMLWcHeatMapElement;
        new (): HTMLWcHeatMapElement;
    };
    interface HTMLElementTagNameMap {
        "wc-heat-map": HTMLWcHeatMapElement;
    }
}
declare namespace LocalJSX {
    interface WcHeatMap {
        "enddate"?: any;
        "height"?: number;
        "startdate"?: any;
        "width"?: number;
    }
    interface IntrinsicElements {
        "wc-heat-map": WcHeatMap;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "wc-heat-map": LocalJSX.WcHeatMap & JSXBase.HTMLAttributes<HTMLWcHeatMapElement>;
        }
    }
}
